### PR TITLE
save_image_voxel_size notebook

### PR DESCRIPTION
**Pull request by pr4deepr**
This PR contains:
* [X] a new test-case for the benchmark
  * [X] I hereby confirm that NO LLM-based technology (such as github copilot) was used while writing this benchmark
* [ ] new dependencies in requirements.txt
  * [ ] The environment.yml file was updated using the command `conda env export > environment.yml`
* [ ] new generator-functions allowing to sample from other LLMs
* [ ] new samples (`sample_....jsonl` files)
* [ ] new benchmarking results (`..._results.jsonl` files)
* [ ] documentation update
* [ ] bug fixes 

Related github issue (if relevant): closes #0

closes https://github.com/haesleinhuepf/human-eval-bia/issues/109

Short description:

- Test case for assigning voxel size to an image. It uses aicsimageio and modifies the class method directly to assign pixel size
Its worth checking if the convension I used for assigning voxel size is ok. 
The check(candidate) function saves the test image to temp directory and reloads it. 
Should we add a delete option to remove the image? Its not very large.

How do you think will this influence the benchmark results?
- New addition

Why do you think it makes sense to merge this PR?
- A test case request for save voxel size.

### CODE REVIEW

**Comment by pr4deepr** [comment]
I realized this doesn't exactly save the image.. 
Assuming we want to save and reload within the function?

Also, another method is setting the ome-xml metadata by using the build_ome method in [Ometiffwriter](https://allencellmodeling.github.io/aicsimageio/_modules/aicsimageio/writers/ome_tiff_writer.html#OmeTiffWriter.save)

It would look like this:

```
ome_metadata = OmeTiffWriter.build_ome(
    [i.shape for i in [img_3d]],
    [i.dtype for i in [img_3d]],
    image_name=None,
    physical_pixel_sizes=[reference_voxel_size],
    dimension_order=['ZYX'])

OmeTiffWriter.save(img_3d,img_path,ome_xml=ome_metadata)

```

**Comment by haesleinhuepf** [comment]
The test looks good to me!

> I realized this doesn't exactly save the image..

We could rename the test; or save the image. Then the function could return nothing but might have one more parameter: filename.

More importantly: can you confirm that you didnt use any LLM / copilot etc when writing the test case @pr4deepr ?

**Comment by pr4deepr** [comment]
I think we can save the image and return the filepath.. 

In the check candidate function, we can open the image and verify the pixel size

**Comment by haesleinhuepf** [comment]
Hey @pr4deepr ,

thanks again for these two new test-cases! I just renamed one so that the function has the same name as the notebook. This makes things a bit more consistent. I also put some line breaks in the prompt to make it easier to read (for humans at least).

Thanks again!

Best,
Robert

**Pull request merged**
