### PR TITLE
New Test-Case - Metadata Reading plus some basics image processing

### LINKED ISSUE #141: New test cases suggestions
Hi!
I was wondering if the following test cases might be of interest:

- Reading/adding metadata using with [bioio](https://github.com/bioio-devs/bioio) or tifffile
- Including a couple of test cases with the library [mahotas](https://mahotas.readthedocs.io/en/latest/)
- Convert ROIs coordinates or metadata to data structures that can be used by the library [ezomero ](https://github.com/TheJacksonLaboratory/ezomero) for import in OMERO (i.e convert tabular files to dictionary/lists/tupples). Mostly data wrangling with pandas.

### PR DESCRIPTION
**Pull request by rmassei**
This PR contains:
* [X] a new test-case for the benchmark
  * [X] I hereby confirm that NO LLM-based technology (such as github copilot) was used while writing this benchmark
* [X] new dependencies in requirements.txt
  * [ ] The environment.yml file was updated using the command `conda env export > environment.yml`
* [ ] new generator-functions allowing to sample from other LLMs
* [ ] new samples (`sample_....jsonl` files)
* [ ] new benchmarking results (`..._results.jsonl` files)
* [ ] documentation update
* [ ] bug fixes 

Related github issue (if relevant): closes #0

Short description:
The present PR add the following test-case:

**Metadata Extraction and Reading using different libraries**
- test_cases/image_proprieties_reader.ipynb
- test_cases/read_ome_xml_from_ome_tiff.ipynb
- test_cases/read_ome_xml_from_xml.ipynb
- test_cases/tiff_metadata_reading.ipynb
- test_cases/tiff_metadata_reading_2.ipynb

**Data Wrangling**
- test_cases/convert_rois_coordinates.ipynb
- test_cases/dataframe_column_rename.ipynb
- test_cases/reshape_array_omero.ipynb

**Array Reshaping**:
- test_cases/stack_and_merge.ipynb
- test_cases/rescale_image.ipynb

How do you think will this influence the benchmark results?
- These tasks should not be difficult to solve, especially the data wrangling. It is interesting to see the results of the metadata reading 

Why do you think it makes sense to merge this PR?
- This PR increase the diversity of the cases studies, especially the ones regarding the metadata reading

closes https://github.com/haesleinhuepf/human-eval-bia/issues/141

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
I will take some time for reviewing those @rmassei , but thanks so much for preparing those!

**Comment by rmassei** [comment]
Just realize that I made a mistake, I need to change the prompting for all the test-cases... I am on it!

**Comment by haesleinhuepf** [comment]
no hurry. thanks again!

**Comment by haesleinhuepf** [comment]
Hey Riccardo @rmassei ,

big thanks again for this! These test-cases look great!

I'm now going to merge these into a dev-branch, where we can collect new test cases. Just explaining: If we merged new test-cases now, we would have to re-run all the benchmarks as the new test-cases haven't been tested with the 20+ models we benchmarked so far.

If you are interested in becoming co-author on the manuscript, **please let us know your full name and affiliation** so that we can add you. Also let us know **if you have any conflicts of interest** that should be reported when submitting the paper.

Thanks again!

Best,
Robert

**Comment by haesleinhuepf** [comment]
I removed some test-cases (see issues linked above) and updated names and docstrings of the other ones.

Thanks again for your efforts @rmassei !

**Comment by rmassei** [comment]
Hej @haesleinhuepf ,
thanks a lot for looking into this and sorry if you had to go trough some intensive clean-up :)
I will check the the test cases causing problems an open a new PR.

Regarding my name and affiliation:
Riccardo Massei
Department of Monitoring and Exploration Technologies - Research Data Management Team (RDM)
Department of Ecotoxicology - Group Integrative Toxicology (iTox)

**Pull request merged**
