### PR TITLE
new test cases: image histogram

### PR DESCRIPTION
**Pull request by pr4deepr**
This PR contains:
* [X] a new test-case for the benchmark
  * [X] I hereby confirm that NO LLM-based technology (such as github copilot) was used while writing this benchmark
* [ ] new dependencies in requirements.txt
  * [ ] The environment.yml file was updated using the command `conda env export > environment.yml`
* [ ] new generator-functions allowing to sample from other LLMs
* [ ] new samples (`sample_....jsonl` files)
* [ ] new benchmarking results (`..._results.jsonl` files)
* [ ] documentation update
* [ ] bug fixes 

Related github issue (if relevant): closes #0

Short description:
- As discussed below, I'm adding a test case for generating a histogram given a 2D image
- 
How do you think will this influence the benchmark results?
- Additional image processing test case

Why do you think it makes sense to merge this PR?
- New test case

I can add more test to this PR if it makes it easier. Wanted to check if this is good before creating new test cases

### CODE REVIEW

**Review by haesleinhuepf — COMMENTED** [review]
Hey @pr4deepr ,

awesome! May I suggest a minor [optional] change? We could turn the 5 into a parameter of the function, e.g. num_bins and thus, have a more flexible usecase.

Otherwise, I would just merge this into a dev-branch, where we can collect new test cases. Just explaining: If we merged new test-cases now, we would have to re-run all the benchmarks as the new test-cases haven't been tested with the 18 models we benchmarked so far. I'd say once we have 10 new test cases together, we can do this in one shot limiting effort on the benchmarking side.

Big thanks again!

Best,
Robert

**Comment by pr4deepr** [comment]
I could also keep updating my fork, which is linked to this PR anyway. Would that be easier than a dev-branch in your repo?

**Comment by haesleinhuepf** [comment]
Awesome, thanks! I will merge this into the dev-branch. If you plan to send more test-cases, please send them as separate PR. I also recommend creating a branch on your side. Otherwise it might be hard to sync between forks.

**Comment by haesleinhuepf** [comment]
One more thing @pr4deepr: I would like to add you to our list of co-authors. Can you quickly write down your affiliation, so that I can later copy it into the document? Also, do you have any conflicts of interest to declare, we should mention when submitting the paper?

**Comment by pr4deepr** [comment]
affiliations:

- Centre for Dynamic Imaging, The Walter and Eliza Hall Institute of Medical Research, Parkville, Victoria, 3052, Australia
- Department of Medical Biology, The University of Melbourne, Parkville, Victoria, 3052, Australia

No conflicts of interest to declare

**Pull request merged**
